[
  {"classname": "playwrite-gb-s"},
  {"classname": "belgrano"},
  {"classname": "bangers"},
  {"classname": "averia-sans-libre"},
  {"classname": "asap"},
  {"classname": "arvo"},
  {"classname": "anton"},
  {"classname": "andika"},
  {"classname": "amatic-sc"},
  {"classname": "almendra"},
  {"classname": "acme"},
  {"classname": "abril-fatface"},
  {"classname": "caveat"},
  {"classname": "rajdhani"},
  {"classname": "lobster"},
  {"classname": "lilita-one"},
  {"classname": "chakra-petch"},
  {"classname": "archivo-black"},
  {"classname": "updock"},
  {"classname": "dancing-script"},
  {"classname": "fira-sans"},
  {"classname": "space-grotesk"},
  {"classname": "dynapuff"},
  {"classname": "pt-serif"},
  {"classname": "bona-nova-sc"},
  {"classname": "bebas-neue "},
  {"classname": "quicksand"},
  {"classname": "oxanium"},
  {"classname": "playfair-display"},
  {"classname": "noto-sans"},
  {"classname": "inter"}
]